"""empty message

Revision ID: 27ce3ce08154
Revises: 5d5cc885fe7d
Create Date: 2020-02-29 08:15:08.286061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27ce3ce08154'
down_revision = '5d5cc885fe7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'date')
    op.add_column('venue', sa.Column('genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.add_column('shows', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
